name: failure_test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "This works"

      - name: Step 2 - intentionally fail
        run: exit 1

      - name: Success step
        if: ${{ success() }}
        run: echo "Everything succeeded"

      - name: Failure step
        if: ${{ failure() }}
        run: echo "Something failed!"