name : job_success_fails

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - run : echo "abcd"

      - if : ${{success()}}
        run : echo " hi"

      - if : ${{ failure()}}
        run : echo "no"