name : practise_test

on:
  workflow_dispatch:

env:
  APP_NAME : FastAPI practise
jobs:
  job1:
    runs-on : ubuntu-latest
    env:
      APP_NAME : FastAPI practise
    name : check_app
    steps:
      - uses : actions/checkout@v4
        with:
          repository : RaGuL-26/cicd-project-helping
          path : fastapi
      - run : echo ${{ env.APP_NAME }}
      - run : echo $APP_NAME
      - run : pip install -r fastapi/requirements.txt
  
  job2:
    name : run_tests
    needs : job1
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v4
        with:
          repository : RaGuL-26/cicd_learning/javas
          path : javafile
      - run : |
          javac hello.java
          java hello


  job3:
    name: final_status
    needs : job2
    runs-on: ubuntu-latest
    steps:
      - run : echo "pipeline completed"

    



      



