name : cicd_envtesting

on:
    workflow_dispatch:

env:
    app_name: myapp
    my_name : ragul

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - run : |
                echo : "app name = $app_name"
                echo : "using : $my_name"
                echo : "${{secrets.PASS_WORD}}"
